-- Autostart (exec-once equivalent)
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
  hl.exec_cmd("systemctl --user start hypridle.service")
  hl.exec_cmd("systemctl --user start hyprmoncfgd.service")
  hl.exec_cmd("systemctl --user start quickshell.service")
  hl.exec_cmd("clipse -listen")
  hl.exec_cmd("udiskie")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("fcitx5 -d --replace")
end)
